---
- name: Certbot command apply
  shell: >-
    certbot certonly --apache\
                     --non-interactive\
                     --agree-tos\
                     --email {{ certbot_account_email }}\
                     --domains {{ certbot_domain_name }}\
                     --force-renewal\
                     --http-01-port {{ certbot_http_port }}\
                     {% if certbot_dry_run %} --dry-run {% endif %}    
  register: certbot_return

- name: Debug certbot command return just to have an ouput
  debug:
    var: certbot_return.stdout_lines

- name: Restart {{ certbot_service_to_restart }}
  service:
    name: "{{ certbot_service_to_restart }}"
    state: restarted
  when: 
    - certbot_service_to_restart is defined
    - certbot_service_to_restart | length > 0
