variables:
  CUR_DIR: "$CI_PROJECT_DIR"
  TERM: "xterm-256color"
  TERMINFO: "/etc/terminfo"
  DEBIAN_FRONTEND: "noninteractive"

stages:
  - lint

before_script:
  - if [ ! "$(grep -ir "direnv export bash" ~/.bashrc)" ];then echo 'eval "$(direnv export bash)"' >> ~/.bashrc; fi && direnv allow . && source ~/.bashrc
  - make env

lint:
  stage: lint
  tags: 
    - deployment
  script:
    - make lint
