---
- name: Ensure apt cache
  apt:
    update_cache: true
  changed_when: false

- name: Install APT dependencies
  apt:
    name: "{{ __certbot_required_apt_packages }}"
    state: present

- name: Install Certbot APT package
  apt:
    name: python3-certbot-dns-ovh
    state: latest
