---
- name: Load os-specific vars
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __certbot_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars

- name: Load certbot specific method tasks
  include_tasks: "{{ certbot_challenge_method }}/main.yml"
