---
- name: Load os-specific vars
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __certbot_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars

- name: Install ansible-role-certbot APT dependencies
  include_tasks: inc/_install.yml

- name: APPLY - Generate let's encrypt certificate  
  include_tasks: "certbot/{{ certbot_challenge_method }}/main.yml"
